"""
Trading logger — writes all paper-trading events to CSV.
Supports the extended IBKR log format (fills, slippage, latency, R, fees).
"""

import csv
import logging
from datetime import datetime
from pathlib import Path
from typing import Optional

from ..core.models import Fill, OrderIntent, Trade

log = logging.getLogger(__name__)

# ── Full column schema for paper_trading_ibkr.csv ────────────────────────────
_IBKR_FIELDS = [
    "timestamp",
    "symbol",
    "signal_id",
    "event_type",
    # Intent fields
    "side",
    "entry_type",
    "entry_price_intent",
    "sl_price",
    "tp_price",
    "ttl_bars",
    # Order IDs
    "parentOrderId",
    "tpOrderId",
    "slOrderId",
    # Lifecycle timestamps
    "order_create_time",
    "fill_time",
    "fill_price",
    "exit_time",
    "exit_price",
    "exit_reason",
    # Execution quality
    "latency_ms",
    "slippage_entry_pips",
    "slippage_exit_pips",
    "realized_R",
    "commissions",
    "spread_at_entry",
    # Status / diagnostics
    "status_timeline",
    "notes",
]


class TradingLogger:
    """
    Logs all trading events to CSV.

    Two files are maintained:
      • paper_trading_ibkr.csv  — detailed per-event IBKR log (new format)
      • paper_trading.csv       — legacy simple log (backward compat)
    """

    def __init__(self, log_dir: str = "logs"):
        self.log_dir = Path(log_dir)
        self.log_dir.mkdir(parents=True, exist_ok=True)

        self.ibkr_log = self.log_dir / "paper_trading_ibkr.csv"
        self.legacy_log = self.log_dir / "paper_trading.csv"

        self._ensure_headers()

    # ── Header initialisation ─────────────────────────────────────────────────

    def _ensure_headers(self):
        if not self.ibkr_log.exists():
            self._write_header(self.ibkr_log, _IBKR_FIELDS)
        if not self.legacy_log.exists():
            self._write_header(self.legacy_log, [
                "timestamp", "symbol", "signal_id", "event_type",
                "side", "entry_type", "entry_price_intent", "sl_price", "tp_price",
                "order_id", "order_create_time", "fill_time", "fill_price",
                "exit_time", "exit_price", "exit_reason",
                "slippage_pips", "latency_ms", "R_multiple_realized",
                "spread_at_entry", "pnl", "notes",
            ])

    @staticmethod
    def _write_header(path: Path, fields: list):
        with open(path, "w", newline="", encoding="utf-8") as f:
            csv.writer(f).writerow(fields)

    # ── Public logging API ────────────────────────────────────────────────────

    def log_intent(self, intent: OrderIntent, notes: str = ""):
        """Log signal/intent generated by strategy."""
        row = {
            "timestamp": datetime.utcnow().isoformat(),
            "symbol": intent.symbol,
            "signal_id": intent.signal_id,
            "event_type": "INTENT",
            "side": intent.side.value,
            "entry_type": intent.entry_type.value,
            "entry_price_intent": intent.entry_price or "",
            "sl_price": intent.sl_price,
            "tp_price": intent.tp_price,
            "ttl_bars": intent.ttl_bars,
            "notes": notes,
        }
        self._append(self.ibkr_log, _IBKR_FIELDS, row)
        self._append_legacy(row, event_type="INTENT", order_id="", notes=notes)

    def log_order_placed(self, intent: OrderIntent, parent_id: str,
                         tp_id: str = "", sl_id: str = ""):
        """Log bracket order submission."""
        row = {
            "timestamp": datetime.utcnow().isoformat(),
            "symbol": intent.symbol,
            "signal_id": intent.signal_id,
            "event_type": "ORDER_PLACED",
            "side": intent.side.value,
            "entry_type": intent.entry_type.value,
            "entry_price_intent": intent.entry_price or "",
            "sl_price": intent.sl_price,
            "tp_price": intent.tp_price,
            "ttl_bars": intent.ttl_bars,
            "parentOrderId": parent_id,
            "tpOrderId": tp_id,
            "slOrderId": sl_id,
            "order_create_time": datetime.utcnow().isoformat(),
        }
        self._append(self.ibkr_log, _IBKR_FIELDS, row)
        self._append_legacy(row, event_type="ORDER_PLACED", order_id=parent_id)

    def log_fill(self, fill: Fill):
        """Log entry fill event."""
        row = {
            "timestamp": datetime.utcnow().isoformat(),
            "symbol": fill.symbol,
            "signal_id": fill.signal_id,
            "event_type": "FILL",
            "side": fill.side.value,
            "parentOrderId": fill.order_id,
            "fill_time": fill.timestamp.isoformat(),
            "fill_price": fill.fill_price,
            "slippage_entry_pips": fill.slippage_pips,
            "latency_ms": fill.latency_ms,
            "spread_at_entry": fill.spread_at_fill,
        }
        self._append(self.ibkr_log, _IBKR_FIELDS, row)
        self._append_legacy(row, event_type="FILL", order_id=fill.order_id,
                             slippage_pips=fill.slippage_pips,
                             latency_ms=fill.latency_ms,
                             fill_price=fill.fill_price,
                             spread=fill.spread_at_fill)

    def log_exit_row(self, row: dict):
        """
        Log a completed trade row dict as returned by
        IBKRExecutionEngine._record_to_log_row().
        """
        row.setdefault("event_type", "TRADE_CLOSED")
        self._append(self.ibkr_log, _IBKR_FIELDS, row)

    def log_trade_closed(self, trade: Trade):
        """Log closed trade (legacy model)."""
        row = {
            "timestamp": datetime.utcnow().isoformat(),
            "symbol": trade.symbol,
            "signal_id": trade.signal_id,
            "event_type": "TRADE_CLOSED",
            "side": trade.side.value,
            "fill_price": trade.entry_price,
            "exit_time": trade.exit_time.isoformat(),
            "exit_price": trade.exit_price,
            "exit_reason": trade.exit_reason.value,
            "realized_R": trade.R_multiple,
        }
        self._append(self.ibkr_log, _IBKR_FIELDS, row)

    def log_risk_block(self, intent: OrderIntent, reason: str):
        """Log when a trade is blocked by risk management."""
        row = {
            "timestamp": datetime.utcnow().isoformat(),
            "symbol": intent.symbol,
            "signal_id": intent.signal_id,
            "event_type": "RISK_BLOCK",
            "side": intent.side.value,
            "notes": reason,
        }
        self._append(self.ibkr_log, _IBKR_FIELDS, row)
        self._append_legacy(row, event_type="RISK_BLOCK", notes=reason)

    def log_kill_switch(self, reason: str):
        row = {
            "timestamp": datetime.utcnow().isoformat(),
            "event_type": "KILL_SWITCH",
            "notes": reason,
        }
        self._append(self.ibkr_log, _IBKR_FIELDS, row)

    # ── Low-level writers ─────────────────────────────────────────────────────

    @staticmethod
    def _append(path: Path, fields: list, data: dict):
        with open(path, "a", newline="", encoding="utf-8") as f:
            w = csv.DictWriter(f, fieldnames=fields, extrasaction="ignore")
            w.writerow({k: data.get(k, "") for k in fields})

    def _append_legacy(self, data: dict, *, event_type: str = "",
                       order_id: str = "", notes: str = "",
                       slippage_pips: float = 0.0, latency_ms: float = 0.0,
                       fill_price: float = 0.0, spread: float = 0.0):
        legacy_fields = [
            "timestamp", "symbol", "signal_id", "event_type",
            "side", "entry_type", "entry_price_intent", "sl_price", "tp_price",
            "order_id", "order_create_time", "fill_time", "fill_price",
            "exit_time", "exit_price", "exit_reason",
            "slippage_pips", "latency_ms", "R_multiple_realized",
            "spread_at_entry", "pnl", "notes",
        ]
        row = {k: data.get(k, "") for k in legacy_fields}
        row["event_type"] = event_type or data.get("event_type", "")
        row["order_id"] = order_id or data.get("parentOrderId", "")
        row["slippage_pips"] = slippage_pips or data.get("slippage_entry_pips", "")
        row["latency_ms"] = latency_ms or data.get("latency_ms", "")
        row["fill_price"] = fill_price or data.get("fill_price", "")
        row["R_multiple_realized"] = data.get("realized_R", "")
        row["spread_at_entry"] = spread or data.get("spread_at_entry", "")
        row["notes"] = notes or data.get("notes", "")
        self._append(self.legacy_log, legacy_fields, row)
